version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    commit-message:
      prefix: "deps(gomod)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
